set shell := ["zsh", "-uc"]

here := justfile_directory()
mamba_env_name := "tau2mumumu-dask-condor-py311"

default: help

alias h := help
help:
    just -l -f {{justfile()}}

alias i:= install
install:
    micromamba create -y -f environment.yaml

alias r := run
run:
    eval "$(micromamba shell hook --shell zsh)" \
        && micromamba activate {{mamba_env_name}} \
        && python ./test-condor.py
